spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/upi_mesh}
spring.datasource.username=${DB_USERNAME:upimesh_dev}
spring.datasource.password=${DB_PASSWORD:upimesh_dev}
spring.flyway.locations=classpath:db/migration,classpath:db/demo-migration
spring.data.redis.port=${REDIS_PORT:6379}
